package session5;

// Generated by Selenium IDE
import org.junit.Assert;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "/Users/olegsirko/Downloads/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void search() {
    driver.get("https://itea.ua/");
    driver.manage().window().setSize(new Dimension(1440, 790));


    driver.findElement(By.cssSelector(".header-search #s")).sendKeys("qa automation");
    driver.findElement(By.cssSelector(".header-search #s")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".articleNew")).click();
    driver.findElement(By.cssSelector("div:nth-child(3) > .clearfix")).click();
    int size = driver.findElements(By.cssSelector("div:nth-child(3) > .btn")).size();
    assertEquals(size, 1);
    driver.findElement(By.cssSelector("div:nth-child(3) > .btn")).click();
  }
}
